/*
###############################################################
#  Generated by:      Cadence Encounter 14.26-s039_1
#  OS:                Linux x86_64(Host ID EEX052)
#  Generated on:      Thu May 13 15:20:48 2021
#  Design:            median_filter
#  Command:           saveNetlist results/N5R8_median_filter.routed.v
###############################################################
*/
module unit_cell_R_WIDTH8_N5_P_WIDTH3_0 (
	srst, 
	clk, 
	incre_en, 
	X, 
	R_from_plus1, 
	R_from_minus1, 
	P_from_plus1, 
	P_from_minus1, 
	Z_from_minus1, 
	T_from_minus1, 
	R_to_plus1minus1, 
	P_to_plus1minus1, 
	Z_to_plus1, 
	T_to_plus1, 
	clk__L2_N2, 
	clk__L2_N6, 
	clk__L2_N7);
   input srst;
   input clk;
   input incre_en;
   input [7:0] X;
   input [7:0] R_from_plus1;
   input [7:0] R_from_minus1;
   input [2:0] P_from_plus1;
   input [2:0] P_from_minus1;
   input Z_from_minus1;
   input T_from_minus1;
   output [7:0] R_to_plus1minus1;
   output [2:0] P_to_plus1minus1;
   output Z_to_plus1;
   output T_to_plus1;
   input clk__L2_N2;
   input clk__L2_N6;
   input clk__L2_N7;

   // Internal wires
   wire bit_cnt;
   wire N49;
   wire N50;
   wire N51;
   wire N56;
   wire T;
   wire n12;
   wire n13;
   wire n14;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n7;
   wire n8;
   wire n15;
   wire n72;
   wire n73;
   wire n74;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n114;

   DFF_X1 P_reg_0_ (.QN(n14),
	.Q(P_to_plus1minus1[0]),
	.D(N49),
	.CK(clk__L2_N7));
   DFF_X1 P_reg_1_ (.QN(n13),
	.Q(P_to_plus1minus1[1]),
	.D(N50),
	.CK(clk));
   DFF_X1 P_reg_2_ (.QN(n12),
	.Q(P_to_plus1minus1[2]),
	.D(N51),
	.CK(clk));
   NAND4_X1 U70 (.ZN(n46),
	.A4(n48),
	.A3(n47),
	.A2(n102),
	.A1(n103));
   XOR2_X1 U71 (.Z(n44),
	.B(P_to_plus1minus1[2]),
	.A(n49));
   NAND3_X1 U72 (.ZN(n56),
	.A3(n101),
	.A2(n47),
	.A1(n103));
   XOR2_X1 U73 (.Z(n55),
	.B(P_to_plus1minus1[1]),
	.A(n14));
   NAND3_X1 U74 (.ZN(n60),
	.A3(bit_cnt),
	.A2(n47),
	.A1(n57));
   DFF_X1 bit_cnt_reg (.Q(bit_cnt),
	.D(N56),
	.CK(clk__L2_N7));
   DFF_X1 R_reg_7_ (.Q(R_to_plus1minus1[7]),
	.D(n71),
	.CK(clk));
   DFF_X1 R_reg_6_ (.QN(n97),
	.Q(R_to_plus1minus1[6]),
	.D(n64),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_5_ (.Q(R_to_plus1minus1[5]),
	.D(n65),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_4_ (.Q(R_to_plus1minus1[4]),
	.D(n66),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_3_ (.QN(n109),
	.Q(R_to_plus1minus1[3]),
	.D(n67),
	.CK(clk__L2_N2));
   DFF_X1 R_reg_2_ (.QN(n94),
	.Q(R_to_plus1minus1[2]),
	.D(n68),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_1_ (.QN(n93),
	.Q(R_to_plus1minus1[1]),
	.D(n69),
	.CK(clk__L2_N2));
   DFF_X1 R_reg_0_ (.Q(R_to_plus1minus1[0]),
	.D(n70),
	.CK(clk__L2_N2));
   INV_X1 U6 (.ZN(n90),
	.A(X[4]));
   INV_X1 U8 (.ZN(n91),
	.A(X[5]));
   INV_X1 U10 (.ZN(n92),
	.A(X[7]));
   NAND2_X1 U17 (.ZN(n7),
	.A2(n93),
	.A1(X[1]));
   NAND2_X1 U18 (.ZN(n8),
	.A2(X[0]),
	.A1(n81));
   INV_X1 U29 (.ZN(n103),
	.A(n51));
   NOR2_X1 U30 (.ZN(n22),
	.A2(n43),
	.A1(n42));
   AND2_X1 U31 (.ZN(n24),
	.A2(n42),
	.A1(n43));
   NAND2_X1 U32 (.ZN(n39),
	.A2(n43),
	.A1(n104));
   NAND2_X1 U33 (.ZN(n51),
	.A2(Z_to_plus1),
	.A1(n61));
   NOR2_X1 U35 (.ZN(n58),
	.A2(n51),
	.A1(n47));
   OAI21_X1 U36 (.ZN(n50),
	.B2(n51),
	.B1(n48),
	.A(n52));
   INV_X1 U37 (.ZN(n98),
	.A(n72));
   OAI21_X1 U38 (.ZN(n40),
	.B2(n107),
	.B1(n41),
	.A(N56));
   NAND2_X1 U39 (.ZN(n45),
	.A2(n41),
	.A1(n61));
   AND2_X1 U40 (.ZN(n61),
	.A2(incre_en),
	.A1(N56));
   NAND2_X1 U41 (.ZN(n42),
	.A2(1'b1),
	.A1(n41));
   INV_X1 U42 (.ZN(n107),
	.A(incre_en));
   OAI21_X1 U43 (.ZN(n21),
	.B2(n39),
	.B1(srst),
	.A(n40));
   AOI22_X1 U45 (.ZN(n62),
	.B2(n24),
	.B1(P_from_minus1[0]),
	.A2(n23),
	.A1(P_from_plus1[0]));
   OAI21_X1 U46 (.ZN(n48),
	.B2(n13),
	.B1(n39),
	.A(n59));
   AOI22_X1 U47 (.ZN(n59),
	.B2(n24),
	.B1(P_from_minus1[1]),
	.A2(n23),
	.A1(P_from_plus1[1]));
   AOI21_X1 U48 (.ZN(n52),
	.B2(bit_cnt),
	.B1(n57),
	.A(n58));
   OAI221_X1 U49 (.ZN(N51),
	.C2(n45),
	.C1(n44),
	.B2(n100),
	.B1(n102),
	.A(n46));
   INV_X1 U50 (.ZN(n100),
	.A(n50));
   OAI221_X1 U51 (.ZN(N50),
	.C2(n52),
	.C1(n101),
	.B2(n45),
	.B1(n55),
	.A(n56));
   INV_X1 U52 (.ZN(n101),
	.A(n48));
   INV_X1 U53 (.ZN(n88),
	.A(X[1]));
   OAI211_X1 U54 (.ZN(N49),
	.C2(n45),
	.C1(P_to_plus1minus1[0]),
	.B(n99),
	.A(n60));
   INV_X1 U55 (.ZN(n99),
	.A(n58));
   OAI21_X1 U56 (.ZN(n67),
	.B2(n19),
	.B1(n29),
	.A(n30));
   NAND2_X1 U57 (.ZN(n30),
	.A2(n21),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U58 (.ZN(n70),
	.B2(n19),
	.B1(n35),
	.A(n36));
   AOI222_X1 U59 (.ZN(n35),
	.C2(n24),
	.C1(R_from_minus1[0]),
	.B2(n23),
	.B1(R_from_plus1[0]),
	.A2(n22),
	.A1(X[0]));
   NAND2_X1 U60 (.ZN(n36),
	.A2(n21),
	.A1(R_to_plus1minus1[0]));
   OAI21_X1 U61 (.ZN(n69),
	.B2(n19),
	.B1(n33),
	.A(n34));
   AOI222_X1 U62 (.ZN(n33),
	.C2(n24),
	.C1(R_from_minus1[1]),
	.B2(n23),
	.B1(R_from_plus1[1]),
	.A2(n22),
	.A1(X[1]));
   NAND2_X1 U63 (.ZN(n34),
	.A2(n21),
	.A1(R_to_plus1minus1[1]));
   OAI21_X1 U64 (.ZN(n68),
	.B2(n19),
	.B1(n31),
	.A(n32));
   AOI222_X1 U65 (.ZN(n31),
	.C2(n24),
	.C1(R_from_minus1[2]),
	.B2(n23),
	.B1(R_from_plus1[2]),
	.A2(n22),
	.A1(X[2]));
   NAND2_X1 U66 (.ZN(n32),
	.A2(n21),
	.A1(R_to_plus1minus1[2]));
   OAI21_X1 U67 (.ZN(n66),
	.B2(n19),
	.B1(n27),
	.A(n28));
   AOI222_X1 U68 (.ZN(n27),
	.C2(n24),
	.C1(R_from_minus1[4]),
	.B2(n23),
	.B1(R_from_plus1[4]),
	.A2(n22),
	.A1(X[4]));
   NAND2_X1 U69 (.ZN(n28),
	.A2(n21),
	.A1(R_to_plus1minus1[4]));
   OAI21_X1 U75 (.ZN(n65),
	.B2(n19),
	.B1(n25),
	.A(n26));
   AOI222_X1 U76 (.ZN(n25),
	.C2(n24),
	.C1(R_from_minus1[5]),
	.B2(n23),
	.B1(R_from_plus1[5]),
	.A2(n22),
	.A1(X[5]));
   NAND2_X1 U77 (.ZN(n26),
	.A2(n21),
	.A1(R_to_plus1minus1[5]));
   OAI21_X1 U78 (.ZN(n64),
	.B2(n19),
	.B1(n18),
	.A(n20));
   AOI222_X1 U79 (.ZN(n18),
	.C2(n24),
	.C1(R_from_minus1[6]),
	.B2(n23),
	.B1(R_from_plus1[6]),
	.A2(n22),
	.A1(X[6]));
   NAND2_X1 U80 (.ZN(n20),
	.A2(n21),
	.A1(R_to_plus1minus1[6]));
   OAI21_X1 U81 (.ZN(n71),
	.B2(n19),
	.B1(n37),
	.A(n38));
   AOI222_X1 U82 (.ZN(n37),
	.C2(n24),
	.C1(R_from_minus1[7]),
	.B2(n23),
	.B1(R_from_plus1[7]),
	.A2(n22),
	.A1(X[7]));
   NAND2_X1 U83 (.ZN(n38),
	.A2(n21),
	.A1(R_to_plus1minus1[7]));
   INV_X1 U84 (.ZN(n102),
	.A(n53));
   OAI21_X1 U85 (.ZN(n53),
	.B2(n39),
	.B1(n12),
	.A(n54));
   AOI22_X1 U86 (.ZN(n54),
	.B2(n24),
	.B1(P_from_minus1[2]),
	.A2(n23),
	.A1(P_from_plus1[2]));
   INV_X1 U87 (.ZN(n95),
	.A(n78));
   NAND2_X1 U88 (.ZN(n19),
	.A2(n106),
	.A1(n40));
   INV_X1 U89 (.ZN(n106),
	.A(srst));
   NOR2_X1 U90 (.ZN(N56),
	.A2(srst),
	.A1(bit_cnt));
   NOR2_X1 U91 (.ZN(n57),
	.A2(srst),
	.A1(n107));
   INV_X1 U92 (.ZN(Z_to_plus1),
	.A(n41));
   NOR2_X1 U93 (.ZN(n41),
	.A2(Z_from_minus1),
	.A1(n63));
   NOR4_X1 U94 (.ZN(n63),
	.A4(n12),
	.A3(P_to_plus1minus1[0]),
	.A2(P_to_plus1minus1[1]),
	.A1(bit_cnt));
   NAND2_X1 U95 (.ZN(n49),
	.A2(P_to_plus1minus1[1]),
	.A1(P_to_plus1minus1[0]));
   AOI222_X1 U97 (.ZN(n29),
	.C2(n24),
	.C1(R_from_minus1[3]),
	.B2(n23),
	.B1(R_from_plus1[3]),
	.A2(n22),
	.A1(X[3]));
   NAND2_X1 U100 (.ZN(n73),
	.A2(n92),
	.A1(R_to_plus1minus1[7]));
   OAI21_X1 U101 (.ZN(n72),
	.B2(n97),
	.B1(X[6]),
	.A(n73));
   NAND3_X1 U102 (.ZN(n74),
	.A3(X[6]),
	.A2(n97),
	.A1(n73));
   OAI21_X1 U103 (.ZN(n77),
	.B2(n92),
	.B1(R_to_plus1minus1[7]),
	.A(n74));
   OAI21_X1 U107 (.ZN(n78),
	.B2(X[2]),
	.B1(n94),
	.A(n79));
   AOI21_X1 U108 (.ZN(n81),
	.B2(n88),
	.B1(R_to_plus1minus1[1]),
	.A(R_to_plus1minus1[0]));
   NAND2_X1 U109 (.ZN(T),
	.A2(n86),
	.A1(n87));
   INV_X1 U3 (.ZN(n84),
	.A(n108));
   OAI21_X1 U4 (.ZN(n108),
	.B2(n112),
	.B1(n85),
	.A(n111));
   NAND3_X1 U5 (.ZN(n80),
	.A3(n79),
	.A2(n94),
	.A1(X[2]));
   NAND2_X1 U7 (.ZN(n79),
	.A2(n114),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U9 (.ZN(n47),
	.B2(n14),
	.B1(n39),
	.A(n62));
   NOR2_X1 U11 (.ZN(n23),
	.A2(n104),
	.A1(n43));
   INV_X1 U12 (.ZN(n104),
	.A(n42));
   AOI21_X1 U13 (.ZN(n43),
	.B2(1'b1),
	.B1(T),
	.A(Z_to_plus1));
   OAI211_X1 U14 (.ZN(n86),
	.C2(n85),
	.C1(n95),
	.B(n98),
	.A(n84));
   NAND3_X1 U15 (.ZN(T_to_plus1),
	.A3(n87),
	.A2(n86),
	.A1(1'b1));
   AOI21_X1 U16 (.ZN(n87),
	.B2(n98),
	.B1(n76),
	.A(n77));
   OAI21_X1 U20 (.ZN(n76),
	.B2(R_to_plus1minus1[5]),
	.B1(n91),
	.A(n110));
   OR3_X1 U21 (.ZN(n110),
	.A3(n90),
	.A2(R_to_plus1minus1[4]),
	.A1(n82));
   NAND2_X1 U22 (.ZN(n85),
	.A2(n15),
	.A1(n80));
   AOI21_X1 U23 (.ZN(n111),
	.B2(n90),
	.B1(R_to_plus1minus1[4]),
	.A(n82));
   AND2_X1 U24 (.ZN(n82),
	.A2(R_to_plus1minus1[5]),
	.A1(n91));
   NAND2_X1 U25 (.ZN(n112),
	.A2(n7),
	.A1(n8));
   NAND2_X1 U26 (.ZN(n15),
	.A2(n109),
	.A1(X[3]));
   INV_X1 U27 (.ZN(n114),
	.A(X[3]));
endmodule

module unit_cell_R_WIDTH8_N5_P_WIDTH3_4 (
	srst, 
	clk, 
	incre_en, 
	X, 
	R_from_plus1, 
	R_from_minus1, 
	P_from_plus1, 
	P_from_minus1, 
	Z_from_minus1, 
	T_from_minus1, 
	R_to_plus1minus1, 
	P_to_plus1minus1, 
	Z_to_plus1, 
	T_to_plus1, 
	clk__L2_N2, 
	clk__L2_N6, 
	clk__L2_N7);
   input srst;
   input clk;
   input incre_en;
   input [7:0] X;
   input [7:0] R_from_plus1;
   input [7:0] R_from_minus1;
   input [2:0] P_from_plus1;
   input [2:0] P_from_minus1;
   input Z_from_minus1;
   input T_from_minus1;
   output [7:0] R_to_plus1minus1;
   output [2:0] P_to_plus1minus1;
   output Z_to_plus1;
   output T_to_plus1;
   input clk__L2_N2;
   input clk__L2_N6;
   input clk__L2_N7;

   // Internal wires
   wire bit_cnt;
   wire N49;
   wire N50;
   wire N51;
   wire N56;
   wire T;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n15;
   wire n16;
   wire n17;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;

   NAND4_X1 U70 (.ZN(n122),
	.A4(n120),
	.A3(n121),
	.A2(n92),
	.A1(n89));
   XOR2_X1 U71 (.Z(n124),
	.B(P_to_plus1minus1[2]),
	.A(n119));
   NAND3_X1 U72 (.ZN(n112),
	.A3(n91),
	.A2(n121),
	.A1(n89));
   XOR2_X1 U73 (.Z(n113),
	.B(P_to_plus1minus1[1]),
	.A(n151));
   NAND3_X1 U74 (.ZN(n108),
	.A3(bit_cnt),
	.A2(n121),
	.A1(n111));
   DFF_X1 bit_cnt_reg (.Q(bit_cnt),
	.D(N56),
	.CK(clk));
   DFF_X1 R_reg_7_ (.Q(R_to_plus1minus1[7]),
	.D(n97),
	.CK(clk));
   DFF_X1 R_reg_6_ (.QN(n87),
	.Q(R_to_plus1minus1[6]),
	.D(n104),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_5_ (.Q(R_to_plus1minus1[5]),
	.D(n103),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_4_ (.Q(R_to_plus1minus1[4]),
	.D(n102),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_2_ (.QN(n85),
	.Q(R_to_plus1minus1[2]),
	.D(n100),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_1_ (.QN(n84),
	.Q(R_to_plus1minus1[1]),
	.D(n99),
	.CK(clk__L2_N2));
   DFF_X1 R_reg_0_ (.Q(R_to_plus1minus1[0]),
	.D(n98),
	.CK(clk__L2_N2));
   DFF_X1 R_reg_3_ (.QN(n3),
	.Q(R_to_plus1minus1[3]),
	.D(n101),
	.CK(clk__L2_N2));
   DFF_X1 P_reg_1_ (.QN(n152),
	.Q(P_to_plus1minus1[1]),
	.D(N50),
	.CK(clk__L2_N7));
   DFF_X1 P_reg_0_ (.QN(n151),
	.Q(P_to_plus1minus1[0]),
	.D(N49),
	.CK(clk));
   DFF_X1 P_reg_2_ (.QN(n153),
	.Q(P_to_plus1minus1[2]),
	.D(N51),
	.CK(clk__L2_N7));
   AND2_X1 U4 (.ZN(n1),
	.A2(X[3]),
	.A1(n3));
   INV_X1 U5 (.ZN(n80),
	.A(X[3]));
   NAND2_X1 U6 (.ZN(n126),
	.A2(n94),
	.A1(n127));
   AOI21_X1 U7 (.ZN(n116),
	.B2(bit_cnt),
	.B1(n111),
	.A(n110));
   NOR2_X1 U8 (.ZN(n2),
	.A2(n4),
	.A1(n1));
   INV_X1 U9 (.ZN(n76),
	.A(n2));
   OR2_X1 U14 (.ZN(n6),
	.A2(n117),
	.A1(n121));
   NAND2_X1 U15 (.ZN(n129),
	.A2(n125),
	.A1(n93));
   INV_X1 U16 (.ZN(n89),
	.A(n117));
   NOR2_X1 U17 (.ZN(n146),
	.A2(n125),
	.A1(n126));
   AND2_X1 U18 (.ZN(n144),
	.A2(n126),
	.A1(n125));
   NAND2_X1 U20 (.ZN(n117),
	.A2(Z_to_plus1),
	.A1(n107));
   NOR2_X1 U21 (.ZN(n110),
	.A2(n117),
	.A1(n121));
   OAI21_X1 U22 (.ZN(n118),
	.B2(n117),
	.B1(n120),
	.A(n116));
   INV_X1 U23 (.ZN(n88),
	.A(n7));
   OAI21_X1 U24 (.ZN(n128),
	.B2(n96),
	.B1(n127),
	.A(N56));
   NAND2_X1 U25 (.ZN(n123),
	.A2(n127),
	.A1(n107));
   AND2_X1 U26 (.ZN(n107),
	.A2(incre_en),
	.A1(N56));
   INV_X1 U27 (.ZN(n96),
	.A(incre_en));
   OAI21_X1 U28 (.ZN(n147),
	.B2(n129),
	.B1(srst),
	.A(n128));
   AOI22_X1 U29 (.ZN(n106),
	.B2(n144),
	.B1(P_from_minus1[0]),
	.A2(n145),
	.A1(P_from_plus1[0]));
   OAI21_X1 U30 (.ZN(n120),
	.B2(n152),
	.B1(n129),
	.A(n109));
   AOI22_X1 U31 (.ZN(n109),
	.B2(n144),
	.B1(P_from_minus1[1]),
	.A2(n145),
	.A1(P_from_plus1[1]));
   OAI221_X1 U32 (.ZN(N51),
	.C2(n123),
	.C1(n124),
	.B2(n90),
	.B1(n92),
	.A(n122));
   INV_X1 U33 (.ZN(n90),
	.A(n118));
   OAI221_X1 U34 (.ZN(N50),
	.C2(n116),
	.C1(n91),
	.B2(n123),
	.B1(n113),
	.A(n112));
   INV_X1 U35 (.ZN(n91),
	.A(n120));
   INV_X1 U36 (.ZN(n79),
	.A(X[1]));
   OAI211_X1 U37 (.ZN(N49),
	.C2(n123),
	.C1(P_to_plus1minus1[0]),
	.B(n6),
	.A(n108));
   OAI21_X1 U38 (.ZN(n101),
	.B2(n149),
	.B1(n139),
	.A(n138));
   NAND2_X1 U39 (.ZN(n138),
	.A2(n147),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U40 (.ZN(n98),
	.B2(n149),
	.B1(n133),
	.A(n132));
   AOI222_X1 U41 (.ZN(n133),
	.C2(n144),
	.C1(R_from_minus1[0]),
	.B2(n145),
	.B1(R_from_plus1[0]),
	.A2(n146),
	.A1(X[0]));
   NAND2_X1 U42 (.ZN(n132),
	.A2(n147),
	.A1(R_to_plus1minus1[0]));
   OAI21_X1 U43 (.ZN(n99),
	.B2(n149),
	.B1(n135),
	.A(n134));
   AOI222_X1 U44 (.ZN(n135),
	.C2(n144),
	.C1(R_from_minus1[1]),
	.B2(n145),
	.B1(R_from_plus1[1]),
	.A2(n146),
	.A1(X[1]));
   NAND2_X1 U45 (.ZN(n134),
	.A2(n147),
	.A1(R_to_plus1minus1[1]));
   OAI21_X1 U46 (.ZN(n100),
	.B2(n149),
	.B1(n137),
	.A(n136));
   AOI222_X1 U47 (.ZN(n137),
	.C2(n144),
	.C1(R_from_minus1[2]),
	.B2(n145),
	.B1(R_from_plus1[2]),
	.A2(n146),
	.A1(X[2]));
   NAND2_X1 U48 (.ZN(n136),
	.A2(n147),
	.A1(R_to_plus1minus1[2]));
   OAI21_X1 U49 (.ZN(n102),
	.B2(n149),
	.B1(n141),
	.A(n140));
   AOI222_X1 U50 (.ZN(n141),
	.C2(n144),
	.C1(R_from_minus1[4]),
	.B2(n145),
	.B1(R_from_plus1[4]),
	.A2(n146),
	.A1(X[4]));
   NAND2_X1 U52 (.ZN(n140),
	.A2(n147),
	.A1(R_to_plus1minus1[4]));
   OAI21_X1 U53 (.ZN(n103),
	.B2(n149),
	.B1(n143),
	.A(n142));
   AOI222_X1 U54 (.ZN(n143),
	.C2(n144),
	.C1(R_from_minus1[5]),
	.B2(n145),
	.B1(R_from_plus1[5]),
	.A2(n146),
	.A1(X[5]));
   NAND2_X1 U55 (.ZN(n142),
	.A2(n147),
	.A1(R_to_plus1minus1[5]));
   OAI21_X1 U56 (.ZN(n104),
	.B2(n149),
	.B1(n150),
	.A(n148));
   AOI222_X1 U57 (.ZN(n150),
	.C2(n144),
	.C1(R_from_minus1[6]),
	.B2(n145),
	.B1(R_from_plus1[6]),
	.A2(n146),
	.A1(X[6]));
   NAND2_X1 U58 (.ZN(n148),
	.A2(n147),
	.A1(R_to_plus1minus1[6]));
   OAI21_X1 U59 (.ZN(n97),
	.B2(n149),
	.B1(n131),
	.A(n130));
   AOI222_X1 U60 (.ZN(n131),
	.C2(n144),
	.C1(R_from_minus1[7]),
	.B2(n145),
	.B1(R_from_plus1[7]),
	.A2(n146),
	.A1(X[7]));
   NAND2_X1 U61 (.ZN(n130),
	.A2(n147),
	.A1(R_to_plus1minus1[7]));
   INV_X1 U62 (.ZN(n83),
	.A(X[7]));
   INV_X1 U63 (.ZN(n81),
	.A(X[4]));
   INV_X1 U64 (.ZN(n82),
	.A(X[5]));
   INV_X1 U65 (.ZN(n92),
	.A(n115));
   OAI21_X1 U66 (.ZN(n115),
	.B2(n129),
	.B1(n153),
	.A(n114));
   AOI22_X1 U67 (.ZN(n114),
	.B2(n144),
	.B1(P_from_minus1[2]),
	.A2(n145),
	.A1(P_from_plus1[2]));
   INV_X1 U68 (.ZN(n86),
	.A(n16));
   NAND2_X1 U69 (.ZN(n149),
	.A2(n95),
	.A1(n128));
   INV_X1 U75 (.ZN(n95),
	.A(srst));
   NOR2_X1 U76 (.ZN(N56),
	.A2(srst),
	.A1(bit_cnt));
   NOR2_X1 U77 (.ZN(n111),
	.A2(srst),
	.A1(n96));
   INV_X1 U78 (.ZN(Z_to_plus1),
	.A(n127));
   NOR2_X1 U79 (.ZN(n127),
	.A2(Z_from_minus1),
	.A1(n105));
   NOR4_X1 U80 (.ZN(n105),
	.A4(n153),
	.A3(P_to_plus1minus1[0]),
	.A2(P_to_plus1minus1[1]),
	.A1(bit_cnt));
   NAND2_X1 U81 (.ZN(n119),
	.A2(P_to_plus1minus1[1]),
	.A1(P_to_plus1minus1[0]));
   AOI222_X1 U82 (.ZN(n139),
	.C2(n144),
	.C1(R_from_minus1[3]),
	.B2(n145),
	.B1(R_from_plus1[3]),
	.A2(n146),
	.A1(X[3]));
   INV_X1 U83 (.ZN(n94),
	.A(T_from_minus1));
   NAND2_X1 U84 (.ZN(n8),
	.A2(n83),
	.A1(R_to_plus1minus1[7]));
   OAI21_X1 U85 (.ZN(n7),
	.B2(n87),
	.B1(X[6]),
	.A(n8));
   NAND3_X1 U86 (.ZN(n9),
	.A3(X[6]),
	.A2(n87),
	.A1(n8));
   OAI21_X1 U87 (.ZN(n15),
	.B2(n83),
	.B1(R_to_plus1minus1[7]),
	.A(n9));
   AND2_X1 U88 (.ZN(n73),
	.A2(n82),
	.A1(R_to_plus1minus1[5]));
   OR3_X1 U89 (.ZN(n10),
	.A3(n81),
	.A2(R_to_plus1minus1[4]),
	.A1(n73));
   OAI21_X1 U90 (.ZN(n11),
	.B2(n82),
	.B1(R_to_plus1minus1[5]),
	.A(n10));
   OAI21_X1 U93 (.ZN(n16),
	.B2(X[2]),
	.B1(n85),
	.A(n17));
   AOI21_X1 U94 (.ZN(n72),
	.B2(n79),
	.B1(R_to_plus1minus1[1]),
	.A(R_to_plus1minus1[0]));
   AOI22_X1 U95 (.ZN(n74),
	.B2(X[0]),
	.B1(n72),
	.A2(n84),
	.A1(X[1]));
   AOI221_X1 U96 (.ZN(n75),
	.C2(n81),
	.C1(R_to_plus1minus1[4]),
	.B2(n2),
	.B1(n74),
	.A(n73));
   OAI21_X1 U3 (.ZN(n121),
	.B2(n151),
	.B1(n129),
	.A(n106));
   NOR2_X2 U10 (.ZN(n145),
	.A2(n93),
	.A1(n125));
   INV_X1 U11 (.ZN(n93),
	.A(n126));
   AOI21_X1 U12 (.ZN(n125),
	.B2(n94),
	.B1(T),
	.A(Z_to_plus1));
   OR2_X1 U13 (.ZN(T_to_plus1),
	.A2(T),
	.A1(T_from_minus1));
   NAND2_X1 U19 (.ZN(T),
	.A2(n155),
	.A1(n154));
   AOI21_X1 U51 (.ZN(n154),
	.B2(n11),
	.B1(n88),
	.A(n15));
   OAI211_X1 U91 (.ZN(n155),
	.C2(n76),
	.C1(n86),
	.B(n88),
	.A(n75));
   AND3_X1 U92 (.ZN(n4),
	.A3(n17),
	.A2(X[2]),
	.A1(n85));
   NAND2_X1 U97 (.ZN(n17),
	.A2(R_to_plus1minus1[3]),
	.A1(n80));
endmodule

module unit_cell_R_WIDTH8_N5_P_WIDTH3_3 (
	srst, 
	clk, 
	incre_en, 
	X, 
	R_from_plus1, 
	R_from_minus1, 
	P_from_plus1, 
	P_from_minus1, 
	Z_from_minus1, 
	T_from_minus1, 
	R_to_plus1minus1, 
	P_to_plus1minus1, 
	Z_to_plus1, 
	T_to_plus1, 
	clk__L2_N3, 
	clk__L2_N2, 
	clk__L2_N1, 
	clk__L2_N5, 
	clk__L2_N6, 
	clk__L2_N7);
   input srst;
   input clk;
   input incre_en;
   input [7:0] X;
   input [7:0] R_from_plus1;
   input [7:0] R_from_minus1;
   input [2:0] P_from_plus1;
   input [2:0] P_from_minus1;
   input Z_from_minus1;
   input T_from_minus1;
   output [7:0] R_to_plus1minus1;
   output [2:0] P_to_plus1minus1;
   output Z_to_plus1;
   output T_to_plus1;
   input clk__L2_N3;
   input clk__L2_N2;
   input clk__L2_N1;
   input clk__L2_N5;
   input clk__L2_N6;
   input clk__L2_N7;

   // Internal wires
   wire FE_OFN3_n144;
   wire bit_cnt;
   wire N49;
   wire N50;
   wire N51;
   wire N56;
   wire T;
   wire n2;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n15;
   wire n16;
   wire n17;
   wire n72;
   wire n73;
   wire n74;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;

   BUF_X1 FE_OFC3_n144 (.Z(FE_OFN3_n144),
	.A(n144));
   NAND4_X1 U70 (.ZN(n121),
	.A4(n119),
	.A3(n120),
	.A2(n91),
	.A1(n88));
   XOR2_X1 U71 (.Z(n123),
	.B(P_to_plus1minus1[2]),
	.A(n118));
   NAND3_X1 U72 (.ZN(n111),
	.A3(n90),
	.A2(n120),
	.A1(n88));
   XOR2_X1 U73 (.Z(n112),
	.B(P_to_plus1minus1[1]),
	.A(n150));
   NAND3_X1 U74 (.ZN(n107),
	.A3(bit_cnt),
	.A2(n120),
	.A1(n110));
   DFF_X1 bit_cnt_reg (.Q(bit_cnt),
	.D(N56),
	.CK(clk__L2_N3));
   DFF_X1 R_reg_0_ (.Q(R_to_plus1minus1[0]),
	.D(n97),
	.CK(clk__L2_N2));
   DFF_X1 R_reg_7_ (.Q(R_to_plus1minus1[7]),
	.D(n96),
	.CK(clk__L2_N3));
   DFF_X1 R_reg_6_ (.QN(n86),
	.Q(R_to_plus1minus1[6]),
	.D(n103),
	.CK(clk__L2_N1));
   DFF_X1 R_reg_5_ (.Q(R_to_plus1minus1[5]),
	.D(n102),
	.CK(clk));
   DFF_X1 R_reg_4_ (.Q(R_to_plus1minus1[4]),
	.D(n101),
	.CK(clk__L2_N6));
   DFF_X1 R_reg_3_ (.Q(R_to_plus1minus1[3]),
	.D(n100),
	.CK(clk__L2_N2));
   DFF_X1 R_reg_2_ (.QN(n83),
	.Q(R_to_plus1minus1[2]),
	.D(n99),
	.CK(clk));
   DFF_X1 R_reg_1_ (.QN(n82),
	.Q(R_to_plus1minus1[1]),
	.D(n98),
	.CK(clk));
   DFF_X1 P_reg_1_ (.QN(n151),
	.Q(P_to_plus1minus1[1]),
	.D(N50),
	.CK(clk__L2_N5));
   DFF_X1 P_reg_0_ (.QN(n150),
	.Q(P_to_plus1minus1[0]),
	.D(N49),
	.CK(clk__L2_N1));
   DFF_X1 P_reg_2_ (.QN(n152),
	.Q(P_to_plus1minus1[2]),
	.D(N51),
	.CK(clk__L2_N7));
   AOI21_X1 U3 (.ZN(n124),
	.B2(T),
	.B1(n93),
	.A(Z_to_plus1));
   OR2_X1 U4 (.ZN(T_to_plus1),
	.A2(T),
	.A1(T_from_minus1));
   NAND2_X1 U5 (.ZN(n125),
	.A2(n93),
	.A1(n126));
   AOI21_X1 U6 (.ZN(n115),
	.B2(bit_cnt),
	.B1(n110),
	.A(n109));
   OAI21_X1 U8 (.ZN(n120),
	.B2(n150),
	.B1(n128),
	.A(n105));
   AND2_X1 U9 (.ZN(n143),
	.A2(n125),
	.A1(n124));
   OR2_X1 U10 (.ZN(n2),
	.A2(n116),
	.A1(n120));
   NOR2_X1 U12 (.ZN(n144),
	.A2(n92),
	.A1(n124));
   INV_X1 U13 (.ZN(n88),
	.A(n116));
   INV_X1 U14 (.ZN(n92),
	.A(n125));
   NAND2_X1 U15 (.ZN(n116),
	.A2(Z_to_plus1),
	.A1(n106));
   NOR2_X1 U16 (.ZN(n109),
	.A2(n116),
	.A1(n120));
   OAI21_X1 U17 (.ZN(n117),
	.B2(n116),
	.B1(n119),
	.A(n115));
   INV_X1 U18 (.ZN(n87),
	.A(n4));
   OAI21_X1 U19 (.ZN(n127),
	.B2(n95),
	.B1(n126),
	.A(N56));
   NAND2_X1 U20 (.ZN(n122),
	.A2(n126),
	.A1(n106));
   AND2_X1 U21 (.ZN(n106),
	.A2(incre_en),
	.A1(N56));
   INV_X1 U22 (.ZN(n95),
	.A(incre_en));
   OAI21_X1 U23 (.ZN(n146),
	.B2(n128),
	.B1(srst),
	.A(n127));
   INV_X1 U24 (.ZN(n85),
	.A(n74));
   AOI22_X1 U25 (.ZN(n105),
	.B2(n143),
	.B1(P_from_minus1[0]),
	.A2(FE_OFN3_n144),
	.A1(P_from_plus1[0]));
   OAI21_X1 U26 (.ZN(n119),
	.B2(n151),
	.B1(n128),
	.A(n108));
   AOI22_X1 U27 (.ZN(n108),
	.B2(n143),
	.B1(P_from_minus1[1]),
	.A2(FE_OFN3_n144),
	.A1(P_from_plus1[1]));
   OAI221_X1 U28 (.ZN(N51),
	.C2(n122),
	.C1(n123),
	.B2(n89),
	.B1(n91),
	.A(n121));
   INV_X1 U29 (.ZN(n89),
	.A(n117));
   OAI221_X1 U30 (.ZN(N50),
	.C2(n115),
	.C1(n90),
	.B2(n122),
	.B1(n112),
	.A(n111));
   INV_X1 U31 (.ZN(n90),
	.A(n119));
   INV_X1 U32 (.ZN(n77),
	.A(X[1]));
   OAI211_X1 U33 (.ZN(N49),
	.C2(n122),
	.C1(P_to_plus1minus1[0]),
	.B(n2),
	.A(n107));
   OAI21_X1 U34 (.ZN(n100),
	.B2(n148),
	.B1(n138),
	.A(n137));
   NAND2_X1 U35 (.ZN(n137),
	.A2(n146),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U36 (.ZN(n97),
	.B2(n148),
	.B1(n132),
	.A(n131));
   AOI222_X1 U37 (.ZN(n132),
	.C2(n143),
	.C1(R_from_minus1[0]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[0]),
	.A2(n145),
	.A1(X[0]));
   NAND2_X1 U38 (.ZN(n131),
	.A2(n146),
	.A1(R_to_plus1minus1[0]));
   OAI21_X1 U39 (.ZN(n98),
	.B2(n148),
	.B1(n134),
	.A(n133));
   AOI222_X1 U40 (.ZN(n134),
	.C2(n143),
	.C1(R_from_minus1[1]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[1]),
	.A2(n145),
	.A1(X[1]));
   NAND2_X1 U41 (.ZN(n133),
	.A2(n146),
	.A1(R_to_plus1minus1[1]));
   OAI21_X1 U42 (.ZN(n99),
	.B2(n148),
	.B1(n136),
	.A(n135));
   AOI222_X1 U43 (.ZN(n136),
	.C2(n143),
	.C1(R_from_minus1[2]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[2]),
	.A2(n145),
	.A1(X[2]));
   NAND2_X1 U44 (.ZN(n135),
	.A2(n146),
	.A1(R_to_plus1minus1[2]));
   OAI21_X1 U45 (.ZN(n101),
	.B2(n148),
	.B1(n140),
	.A(n139));
   AOI222_X1 U46 (.ZN(n140),
	.C2(n143),
	.C1(R_from_minus1[4]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[4]),
	.A2(n145),
	.A1(X[4]));
   NAND2_X1 U47 (.ZN(n139),
	.A2(n146),
	.A1(R_to_plus1minus1[4]));
   OAI21_X1 U48 (.ZN(n102),
	.B2(n148),
	.B1(n142),
	.A(n141));
   AOI222_X1 U49 (.ZN(n142),
	.C2(n143),
	.C1(R_from_minus1[5]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[5]),
	.A2(n145),
	.A1(X[5]));
   NAND2_X1 U50 (.ZN(n141),
	.A2(n146),
	.A1(R_to_plus1minus1[5]));
   OAI21_X1 U51 (.ZN(n103),
	.B2(n148),
	.B1(n149),
	.A(n147));
   AOI222_X1 U52 (.ZN(n149),
	.C2(n143),
	.C1(R_from_minus1[6]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[6]),
	.A2(n145),
	.A1(X[6]));
   NAND2_X1 U53 (.ZN(n147),
	.A2(n146),
	.A1(R_to_plus1minus1[6]));
   OAI21_X1 U54 (.ZN(n96),
	.B2(n148),
	.B1(n130),
	.A(n129));
   AOI222_X1 U55 (.ZN(n130),
	.C2(n143),
	.C1(R_from_minus1[7]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[7]),
	.A2(n145),
	.A1(X[7]));
   NAND2_X1 U56 (.ZN(n129),
	.A2(n146),
	.A1(R_to_plus1minus1[7]));
   INV_X1 U57 (.ZN(n81),
	.A(X[7]));
   INV_X1 U58 (.ZN(n79),
	.A(X[4]));
   INV_X1 U59 (.ZN(n80),
	.A(X[5]));
   INV_X1 U60 (.ZN(n91),
	.A(n114));
   OAI21_X1 U61 (.ZN(n114),
	.B2(n128),
	.B1(n152),
	.A(n113));
   AOI22_X1 U62 (.ZN(n113),
	.B2(n143),
	.B1(P_from_minus1[2]),
	.A2(FE_OFN3_n144),
	.A1(P_from_plus1[2]));
   INV_X1 U63 (.ZN(n84),
	.A(n10));
   NAND2_X1 U64 (.ZN(n148),
	.A2(n94),
	.A1(n127));
   INV_X1 U65 (.ZN(n94),
	.A(srst));
   NOR2_X1 U66 (.ZN(N56),
	.A2(srst),
	.A1(bit_cnt));
   NOR2_X1 U67 (.ZN(n110),
	.A2(srst),
	.A1(n95));
   NOR2_X1 U68 (.ZN(n126),
	.A2(Z_from_minus1),
	.A1(n104));
   NOR4_X1 U69 (.ZN(n104),
	.A4(n152),
	.A3(P_to_plus1minus1[0]),
	.A2(P_to_plus1minus1[1]),
	.A1(bit_cnt));
   INV_X1 U75 (.ZN(Z_to_plus1),
	.A(n126));
   NAND2_X1 U76 (.ZN(n118),
	.A2(P_to_plus1minus1[1]),
	.A1(P_to_plus1minus1[0]));
   AOI222_X1 U77 (.ZN(n138),
	.C2(n143),
	.C1(R_from_minus1[3]),
	.B2(FE_OFN3_n144),
	.B1(R_from_plus1[3]),
	.A2(n145),
	.A1(X[3]));
   INV_X1 U78 (.ZN(n78),
	.A(X[3]));
   NOR2_X1 U79 (.ZN(n145),
	.A2(n124),
	.A1(n125));
   NAND2_X1 U80 (.ZN(n128),
	.A2(n124),
	.A1(n92));
   INV_X1 U81 (.ZN(n93),
	.A(T_from_minus1));
   NAND2_X1 U82 (.ZN(n5),
	.A2(n81),
	.A1(R_to_plus1minus1[7]));
   OAI21_X1 U83 (.ZN(n4),
	.B2(n86),
	.B1(X[6]),
	.A(n5));
   NAND3_X1 U84 (.ZN(n6),
	.A3(X[6]),
	.A2(n86),
	.A1(n5));
   OAI21_X1 U85 (.ZN(n9),
	.B2(n81),
	.B1(R_to_plus1minus1[7]),
	.A(n6));
   AND2_X1 U86 (.ZN(n17),
	.A2(n80),
	.A1(R_to_plus1minus1[5]));
   OR3_X1 U87 (.ZN(n7),
	.A3(n79),
	.A2(R_to_plus1minus1[4]),
	.A1(n17));
   OAI21_X1 U88 (.ZN(n8),
	.B2(n80),
	.B1(R_to_plus1minus1[5]),
	.A(n7));
   NAND2_X1 U90 (.ZN(n11),
	.A2(n78),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U91 (.ZN(n10),
	.B2(X[2]),
	.B1(n83),
	.A(n11));
   NAND3_X1 U92 (.ZN(n15),
	.A3(X[2]),
	.A2(n83),
	.A1(n11));
   OAI21_X1 U93 (.ZN(n74),
	.B2(n78),
	.B1(R_to_plus1minus1[3]),
	.A(n15));
   AOI21_X1 U94 (.ZN(n16),
	.B2(n77),
	.B1(R_to_plus1minus1[1]),
	.A(R_to_plus1minus1[0]));
   AOI22_X1 U95 (.ZN(n72),
	.B2(X[0]),
	.B1(n16),
	.A2(n82),
	.A1(X[1]));
   AOI221_X1 U96 (.ZN(n73),
	.C2(n79),
	.C1(R_to_plus1minus1[4]),
	.B2(n85),
	.B1(n72),
	.A(n17));
   NAND2_X1 U89 (.ZN(T),
	.A2(n153),
	.A1(n154));
   AOI21_X1 U97 (.ZN(n153),
	.B2(n8),
	.B1(n87),
	.A(n9));
   OAI211_X1 U98 (.ZN(n154),
	.C2(n74),
	.C1(n84),
	.B(n87),
	.A(n73));
endmodule

module unit_cell_R_WIDTH8_N5_P_WIDTH3_2 (
	srst, 
	clk, 
	incre_en, 
	X, 
	R_from_plus1, 
	R_from_minus1, 
	P_from_plus1, 
	P_from_minus1, 
	Z_from_minus1, 
	T_from_minus1, 
	R_to_plus1minus1, 
	P_to_plus1minus1, 
	Z_to_plus1, 
	T_to_plus1, 
	p, 
	clk__L2_N0, 
	clk__L2_N1, 
	clk__L2_N5);
   input srst;
   input clk;
   input incre_en;
   input [7:0] X;
   input [7:0] R_from_plus1;
   input [7:0] R_from_minus1;
   input [2:0] P_from_plus1;
   input [2:0] P_from_minus1;
   input Z_from_minus1;
   input T_from_minus1;
   output [7:0] R_to_plus1minus1;
   output [2:0] P_to_plus1minus1;
   output Z_to_plus1;
   output T_to_plus1;
   input p;
   input clk__L2_N0;
   input clk__L2_N1;
   input clk__L2_N5;

   // Internal wires
   wire FE_UNCONNECTED_0;
   wire FE_OFN2_n151;
   wire bit_cnt;
   wire N49;
   wire N50;
   wire N51;
   wire N56;
   wire T;
   wire n1;
   wire n3;
   wire n9;
   wire n10;
   wire n11;
   wire n15;
   wire n16;
   wire n17;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n100;
   wire n101;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;

   BUF_X1 FE_OFC2_n151 (.Z(FE_OFN2_n151),
	.A(n151));
   AOI21_X1 U51 (.ZN(n131),
	.B2(T),
	.B1(n100),
	.A(Z_to_plus1));
   NAND4_X1 U70 (.ZN(n128),
	.A4(n126),
	.A3(n127),
	.A2(n97),
	.A1(n93));
   XOR2_X1 U71 (.Z(n130),
	.B(P_to_plus1minus1[2]),
	.A(n125));
   NAND3_X1 U72 (.ZN(n118),
	.A3(n96),
	.A2(n127),
	.A1(n93));
   XOR2_X1 U73 (.Z(n119),
	.B(P_to_plus1minus1[1]),
	.A(n157));
   NAND3_X1 U74 (.ZN(n114),
	.A3(bit_cnt),
	.A2(n127),
	.A1(n117));
   DFF_X1 bit_cnt_reg (.Q(bit_cnt),
	.D(N56),
	.CK(clk__L2_N5));
   DFF_X1 R_reg_7_ (.Q(R_to_plus1minus1[7]),
	.D(n103),
	.CK(clk__L2_N1));
   DFF_X1 R_reg_6_ (.QN(n91),
	.Q(R_to_plus1minus1[6]),
	.D(n110),
	.CK(clk__L2_N1));
   DFF_X1 R_reg_5_ (.Q(R_to_plus1minus1[5]),
	.D(n109),
	.CK(clk));
   DFF_X1 R_reg_4_ (.Q(R_to_plus1minus1[4]),
	.D(n108),
	.CK(clk));
   DFF_X1 R_reg_3_ (.Q(R_to_plus1minus1[3]),
	.D(n107),
	.CK(clk));
   DFF_X1 R_reg_2_ (.QN(n88),
	.Q(R_to_plus1minus1[2]),
	.D(n106),
	.CK(clk));
   DFF_X1 R_reg_1_ (.QN(n87),
	.Q(R_to_plus1minus1[1]),
	.D(n105),
	.CK(clk));
   DFF_X1 R_reg_0_ (.Q(R_to_plus1minus1[0]),
	.D(n104),
	.CK(clk__L2_N0));
   DFF_X1 P_reg_0_ (.QN(n157),
	.Q(P_to_plus1minus1[0]),
	.D(N49),
	.CK(clk__L2_N5));
   DFF_X1 P_reg_1_ (.QN(n158),
	.Q(P_to_plus1minus1[1]),
	.D(N50),
	.CK(clk__L2_N5));
   DFF_X1 P_reg_2_ (.QN(n159),
	.Q(P_to_plus1minus1[2]),
	.D(N51),
	.CK(clk__L2_N1));
   OR2_X1 U4 (.ZN(T_to_plus1),
	.A2(T),
	.A1(T_from_minus1));
   NOR2_X1 U7 (.ZN(n1),
	.A2(n116),
	.A1(n3));
   AND2_X1 U9 (.ZN(n3),
	.A2(bit_cnt),
	.A1(n117));
   INV_X1 U15 (.ZN(n93),
	.A(n123));
   AND2_X1 U16 (.ZN(n150),
	.A2(n132),
	.A1(n131));
   INV_X1 U17 (.ZN(n98),
	.A(n132));
   NAND2_X1 U18 (.ZN(n123),
	.A2(Z_to_plus1),
	.A1(n113));
   OAI21_X1 U19 (.ZN(n124),
	.B2(n123),
	.B1(n126),
	.A(n1));
   INV_X1 U20 (.ZN(n92),
	.A(n9));
   OAI21_X1 U21 (.ZN(n134),
	.B2(p),
	.B1(n133),
	.A(N56));
   NAND2_X1 U22 (.ZN(n129),
	.A2(n133),
	.A1(n113));
   AND2_X1 U23 (.ZN(n113),
	.A2(incre_en),
	.A1(N56));
   INV_X1 U24 (.ZN(Z_to_plus1),
	.A(n133));
   OAI21_X1 U26 (.ZN(n153),
	.B2(n135),
	.B1(srst),
	.A(n134));
   INV_X1 U27 (.ZN(n90),
	.A(n79));
   OAI21_X1 U28 (.ZN(n126),
	.B2(n158),
	.B1(n135),
	.A(n115));
   OAI221_X1 U29 (.ZN(N51),
	.C2(n129),
	.C1(n130),
	.B2(n95),
	.B1(n97),
	.A(n128));
   INV_X1 U30 (.ZN(n95),
	.A(n124));
   OAI221_X1 U31 (.ZN(N50),
	.C2(n1),
	.C1(n96),
	.B2(n129),
	.B1(n119),
	.A(n118));
   INV_X1 U32 (.ZN(n96),
	.A(n126));
   INV_X1 U33 (.ZN(n89),
	.A(n72));
   INV_X1 U34 (.ZN(n82),
	.A(X[1]));
   OAI211_X1 U35 (.ZN(N49),
	.C2(n129),
	.C1(P_to_plus1minus1[0]),
	.B(n94),
	.A(n114));
   INV_X1 U36 (.ZN(n94),
	.A(n116));
   OAI21_X1 U37 (.ZN(n104),
	.B2(n155),
	.B1(n139),
	.A(n138));
   NAND2_X1 U38 (.ZN(n138),
	.A2(n153),
	.A1(R_to_plus1minus1[0]));
   OAI21_X1 U39 (.ZN(n105),
	.B2(n155),
	.B1(n141),
	.A(n140));
   NAND2_X1 U40 (.ZN(n140),
	.A2(n153),
	.A1(R_to_plus1minus1[1]));
   OAI21_X1 U41 (.ZN(n106),
	.B2(n155),
	.B1(n143),
	.A(n142));
   NAND2_X1 U42 (.ZN(n142),
	.A2(n153),
	.A1(R_to_plus1minus1[2]));
   OAI21_X1 U43 (.ZN(n107),
	.B2(n155),
	.B1(n145),
	.A(n144));
   NAND2_X1 U44 (.ZN(n144),
	.A2(n153),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U45 (.ZN(n108),
	.B2(n155),
	.B1(n147),
	.A(n146));
   NAND2_X1 U46 (.ZN(n146),
	.A2(n153),
	.A1(R_to_plus1minus1[4]));
   OAI21_X1 U47 (.ZN(n109),
	.B2(n155),
	.B1(n149),
	.A(n148));
   NAND2_X1 U48 (.ZN(n148),
	.A2(n153),
	.A1(R_to_plus1minus1[5]));
   OAI21_X1 U49 (.ZN(n110),
	.B2(n155),
	.B1(n156),
	.A(n154));
   NAND2_X1 U50 (.ZN(n154),
	.A2(n153),
	.A1(R_to_plus1minus1[6]));
   OAI21_X1 U52 (.ZN(n103),
	.B2(n155),
	.B1(n137),
	.A(n136));
   NAND2_X1 U53 (.ZN(n136),
	.A2(n153),
	.A1(R_to_plus1minus1[7]));
   INV_X1 U54 (.ZN(n86),
	.A(X[7]));
   INV_X1 U55 (.ZN(n84),
	.A(X[4]));
   INV_X1 U56 (.ZN(n85),
	.A(X[5]));
   INV_X1 U57 (.ZN(n97),
	.A(n121));
   OAI21_X1 U58 (.ZN(n121),
	.B2(n135),
	.B1(n159),
	.A(n120));
   NAND2_X1 U59 (.ZN(n155),
	.A2(n101),
	.A1(n134));
   INV_X1 U60 (.ZN(n101),
	.A(srst));
   NOR2_X1 U61 (.ZN(N56),
	.A2(srst),
	.A1(bit_cnt));
   NOR2_X1 U62 (.ZN(n117),
	.A2(srst),
	.A1(p));
   NOR2_X1 U63 (.ZN(n133),
	.A2(Z_from_minus1),
	.A1(n111));
   NOR4_X1 U64 (.ZN(n111),
	.A4(n159),
	.A3(P_to_plus1minus1[0]),
	.A2(P_to_plus1minus1[1]),
	.A1(bit_cnt));
   NAND2_X1 U65 (.ZN(n125),
	.A2(P_to_plus1minus1[1]),
	.A1(P_to_plus1minus1[0]));
   INV_X1 U66 (.ZN(n83),
	.A(X[3]));
   NOR2_X1 U68 (.ZN(n151),
	.A2(n98),
	.A1(n131));
   NAND2_X1 U69 (.ZN(n132),
	.A2(n100),
	.A1(n133));
   NOR2_X1 U75 (.ZN(n152),
	.A2(n131),
	.A1(n132));
   NAND2_X1 U76 (.ZN(n135),
	.A2(n131),
	.A1(n98));
   AOI222_X1 U77 (.ZN(n156),
	.C2(n150),
	.C1(R_from_minus1[6]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[6]),
	.A2(n152),
	.A1(X[6]));
   AOI222_X1 U78 (.ZN(n149),
	.C2(n150),
	.C1(R_from_minus1[5]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[5]),
	.A2(n152),
	.A1(X[5]));
   AOI222_X1 U79 (.ZN(n147),
	.C2(n150),
	.C1(R_from_minus1[4]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[4]),
	.A2(n152),
	.A1(X[4]));
   AOI222_X1 U80 (.ZN(n143),
	.C2(n150),
	.C1(R_from_minus1[2]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[2]),
	.A2(n152),
	.A1(X[2]));
   AOI222_X1 U81 (.ZN(n141),
	.C2(n150),
	.C1(R_from_minus1[1]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[1]),
	.A2(n152),
	.A1(X[1]));
   AOI222_X1 U82 (.ZN(n139),
	.C2(n150),
	.C1(R_from_minus1[0]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[0]),
	.A2(n152),
	.A1(X[0]));
   AOI222_X1 U83 (.ZN(n137),
	.C2(n150),
	.C1(R_from_minus1[7]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[7]),
	.A2(n152),
	.A1(X[7]));
   AOI222_X1 U84 (.ZN(n145),
	.C2(n150),
	.C1(R_from_minus1[3]),
	.B2(FE_OFN2_n151),
	.B1(R_from_plus1[3]),
	.A2(n152),
	.A1(X[3]));
   AOI22_X1 U85 (.ZN(n120),
	.B2(n150),
	.B1(P_from_minus1[2]),
	.A2(FE_OFN2_n151),
	.A1(P_from_plus1[2]));
   AOI22_X1 U86 (.ZN(n115),
	.B2(n150),
	.B1(P_from_minus1[1]),
	.A2(FE_OFN2_n151),
	.A1(P_from_plus1[1]));
   INV_X1 U87 (.ZN(n100),
	.A(T_from_minus1));
   NAND2_X1 U88 (.ZN(n10),
	.A2(n86),
	.A1(R_to_plus1minus1[7]));
   OAI21_X1 U89 (.ZN(n9),
	.B2(n91),
	.B1(X[6]),
	.A(n10));
   NAND3_X1 U90 (.ZN(n11),
	.A3(X[6]),
	.A2(n91),
	.A1(n10));
   OAI21_X1 U91 (.ZN(n17),
	.B2(n86),
	.B1(R_to_plus1minus1[7]),
	.A(n11));
   AND2_X1 U92 (.ZN(n76),
	.A2(n85),
	.A1(R_to_plus1minus1[5]));
   OR3_X1 U93 (.ZN(n15),
	.A3(n84),
	.A2(R_to_plus1minus1[4]),
	.A1(n76));
   OAI21_X1 U94 (.ZN(n16),
	.B2(n85),
	.B1(R_to_plus1minus1[5]),
	.A(n15));
   NAND2_X1 U96 (.ZN(n73),
	.A2(n83),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U97 (.ZN(n72),
	.B2(X[2]),
	.B1(n88),
	.A(n73));
   NAND3_X1 U98 (.ZN(n74),
	.A3(X[2]),
	.A2(n88),
	.A1(n73));
   OAI21_X1 U99 (.ZN(n79),
	.B2(n83),
	.B1(R_to_plus1minus1[3]),
	.A(n74));
   AOI21_X1 U100 (.ZN(n75),
	.B2(n82),
	.B1(R_to_plus1minus1[1]),
	.A(R_to_plus1minus1[0]));
   AOI22_X1 U101 (.ZN(n77),
	.B2(X[0]),
	.B1(n75),
	.A2(n87),
	.A1(X[1]));
   AOI221_X1 U102 (.ZN(n78),
	.C2(n84),
	.C1(R_to_plus1minus1[4]),
	.B2(n90),
	.B1(n77),
	.A(n76));
   NOR2_X1 U3 (.ZN(n116),
	.A2(n123),
	.A1(n127));
   OAI21_X1 U5 (.ZN(n127),
	.B2(n135),
	.B1(n157),
	.A(n160));
   AOI22_X1 U6 (.ZN(n160),
	.B2(FE_OFN2_n151),
	.B1(P_from_plus1[0]),
	.A2(n150),
	.A1(P_from_minus1[0]));
   NAND2_X1 U8 (.ZN(T),
	.A2(n161),
	.A1(n162));
   AOI21_X1 U11 (.ZN(n161),
	.B2(n16),
	.B1(n92),
	.A(n17));
   OAI211_X1 U12 (.ZN(n162),
	.C2(n79),
	.C1(n89),
	.B(n92),
	.A(n78));
endmodule

module unit_cell_R_WIDTH8_N5_P_WIDTH3_1 (
	srst, 
	clk, 
	incre_en, 
	X, 
	R_from_plus1, 
	R_from_minus1, 
	P_from_plus1, 
	P_from_minus1, 
	Z_from_minus1, 
	T_from_minus1, 
	R_to_plus1minus1, 
	P_to_plus1minus1, 
	Z_to_plus1, 
	T_to_plus1, 
	clk__L2_N1, 
	clk__L2_N5);
   input srst;
   input clk;
   input incre_en;
   input [7:0] X;
   input [7:0] R_from_plus1;
   input [7:0] R_from_minus1;
   input [2:0] P_from_plus1;
   input [2:0] P_from_minus1;
   input Z_from_minus1;
   input T_from_minus1;
   output [7:0] R_to_plus1minus1;
   output [2:0] P_to_plus1minus1;
   output Z_to_plus1;
   output T_to_plus1;
   input clk__L2_N1;
   input clk__L2_N5;

   // Internal wires
   wire FE_UNCONNECTED_0;
   wire Z_to_plus10;
   wire bit_cnt;
   wire N49;
   wire N50;
   wire N51;
   wire N56;
   wire T;
   wire n4;
   wire n7;
   wire n8;
   wire n9;
   wire n11;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;

   NAND4_X1 U70 (.ZN(n133),
	.A4(n131),
	.A3(n11),
	.A2(n104),
	.A1(n100));
   XOR2_X1 U71 (.Z(n135),
	.B(P_to_plus1minus1[2]),
	.A(n130));
   NAND3_X1 U72 (.ZN(n123),
	.A3(n103),
	.A2(n11),
	.A1(n100));
   XOR2_X1 U73 (.Z(n124),
	.B(P_to_plus1minus1[1]),
	.A(n162));
   NAND3_X1 U74 (.ZN(n119),
	.A3(bit_cnt),
	.A2(n11),
	.A1(n122));
   DFF_X1 bit_cnt_reg (.Q(bit_cnt),
	.D(N56),
	.CK(clk__L2_N5));
   DFF_X1 R_reg_7_ (.Q(R_to_plus1minus1[7]),
	.D(n108),
	.CK(clk__L2_N1));
   DFF_X1 R_reg_6_ (.QN(n98),
	.Q(R_to_plus1minus1[6]),
	.D(n115),
	.CK(clk));
   DFF_X1 R_reg_5_ (.Q(R_to_plus1minus1[5]),
	.D(n114),
	.CK(clk));
   DFF_X1 R_reg_4_ (.Q(R_to_plus1minus1[4]),
	.D(n113),
	.CK(clk));
   DFF_X1 R_reg_3_ (.Q(R_to_plus1minus1[3]),
	.D(n112),
	.CK(clk));
   DFF_X1 R_reg_2_ (.QN(n95),
	.Q(R_to_plus1minus1[2]),
	.D(n111),
	.CK(clk));
   DFF_X1 R_reg_1_ (.QN(n94),
	.Q(R_to_plus1minus1[1]),
	.D(n110),
	.CK(clk));
   DFF_X1 R_reg_0_ (.Q(R_to_plus1minus1[0]),
	.D(n109),
	.CK(clk));
   DFF_X1 P_reg_0_ (.QN(n162),
	.Q(P_to_plus1minus1[0]),
	.D(N49),
	.CK(clk__L2_N5));
   DFF_X1 P_reg_1_ (.QN(n163),
	.Q(P_to_plus1minus1[1]),
	.D(N50),
	.CK(clk__L2_N5));
   DFF_X1 P_reg_2_ (.QN(n164),
	.Q(P_to_plus1minus1[2]),
	.D(N51),
	.CK(clk__L2_N1));
   OR2_X1 U3 (.ZN(n8),
	.A2(n162),
	.A1(n140));
   NOR2_X4 U5 (.ZN(n156),
	.A2(n7),
	.A1(n136));
   AOI21_X2 U8 (.ZN(n136),
	.B2(T),
	.B1(T_from_minus1),
	.A(Z_to_plus10));
   AND2_X2 U13 (.ZN(n7),
	.A2(T_from_minus1),
	.A1(n138));
   INV_X1 U15 (.ZN(n4),
	.A(n7));
   NAND2_X1 U17 (.ZN(n132),
	.A2(n117),
	.A1(n8));
   NOR2_X1 U18 (.ZN(n121),
	.A2(n128),
	.A1(n132));
   AOI22_X1 U19 (.ZN(n9),
	.B2(n155),
	.B1(P_from_minus1[0]),
	.A2(n156),
	.A1(P_from_plus1[0]));
   OAI21_X1 U21 (.ZN(n11),
	.B2(n162),
	.B1(n140),
	.A(n9));
   INV_X1 U22 (.ZN(n100),
	.A(n128));
   NAND2_X1 U23 (.ZN(n128),
	.A2(Z_to_plus10),
	.A1(n118));
   INV_X1 U24 (.ZN(n99),
	.A(n73));
   INV_X1 U25 (.ZN(n103),
	.A(n131));
   OAI21_X1 U26 (.ZN(n139),
	.B2(n107),
	.B1(n138),
	.A(N56));
   NAND2_X1 U27 (.ZN(n134),
	.A2(n138),
	.A1(n118));
   AND2_X1 U28 (.ZN(n118),
	.A2(incre_en),
	.A1(N56));
   INV_X1 U29 (.ZN(n107),
	.A(incre_en));
   INV_X1 U30 (.ZN(Z_to_plus10),
	.A(n138));
   OAI21_X1 U31 (.ZN(n158),
	.B2(n140),
	.B1(srst),
	.A(n139));
   INV_X1 U32 (.ZN(n97),
	.A(n86));
   OAI21_X1 U33 (.ZN(n131),
	.B2(n163),
	.B1(n140),
	.A(n120));
   INV_X1 U34 (.ZN(n96),
	.A(n79));
   OAI211_X1 U35 (.ZN(N49),
	.C2(n134),
	.C1(P_to_plus1minus1[0]),
	.B(n101),
	.A(n119));
   OAI21_X1 U36 (.ZN(n109),
	.B2(n160),
	.B1(n144),
	.A(n143));
   NAND2_X1 U37 (.ZN(n143),
	.A2(n158),
	.A1(R_to_plus1minus1[0]));
   OAI21_X1 U38 (.ZN(n110),
	.B2(n160),
	.B1(n146),
	.A(n145));
   NAND2_X1 U39 (.ZN(n145),
	.A2(n158),
	.A1(R_to_plus1minus1[1]));
   OAI21_X1 U40 (.ZN(n111),
	.B2(n160),
	.B1(n148),
	.A(n147));
   NAND2_X1 U41 (.ZN(n147),
	.A2(n158),
	.A1(R_to_plus1minus1[2]));
   OAI21_X1 U42 (.ZN(n112),
	.B2(n160),
	.B1(n150),
	.A(n149));
   NAND2_X1 U43 (.ZN(n149),
	.A2(n158),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U44 (.ZN(n113),
	.B2(n160),
	.B1(n152),
	.A(n151));
   NAND2_X1 U45 (.ZN(n151),
	.A2(n158),
	.A1(R_to_plus1minus1[4]));
   OAI21_X1 U46 (.ZN(n114),
	.B2(n160),
	.B1(n154),
	.A(n153));
   NAND2_X1 U47 (.ZN(n153),
	.A2(n158),
	.A1(R_to_plus1minus1[5]));
   OAI21_X1 U48 (.ZN(n115),
	.B2(n160),
	.B1(n161),
	.A(n159));
   NAND2_X1 U49 (.ZN(n159),
	.A2(n158),
	.A1(R_to_plus1minus1[6]));
   OAI21_X1 U50 (.ZN(n108),
	.B2(n160),
	.B1(n142),
	.A(n141));
   NAND2_X1 U51 (.ZN(n141),
	.A2(n158),
	.A1(R_to_plus1minus1[7]));
   INV_X1 U52 (.ZN(n93),
	.A(X[7]));
   INV_X1 U53 (.ZN(n91),
	.A(X[4]));
   INV_X1 U54 (.ZN(n92),
	.A(X[5]));
   INV_X1 U55 (.ZN(n89),
	.A(X[1]));
   INV_X1 U56 (.ZN(n104),
	.A(n126));
   OAI21_X1 U57 (.ZN(n126),
	.B2(n140),
	.B1(n164),
	.A(n125));
   NAND2_X1 U58 (.ZN(n160),
	.A2(n106),
	.A1(n139));
   INV_X1 U59 (.ZN(n106),
	.A(srst));
   NOR2_X1 U60 (.ZN(N56),
	.A2(srst),
	.A1(bit_cnt));
   NOR2_X1 U61 (.ZN(n122),
	.A2(srst),
	.A1(n107));
   NOR4_X1 U63 (.ZN(n116),
	.A4(n164),
	.A3(P_to_plus1minus1[0]),
	.A2(P_to_plus1minus1[1]),
	.A1(bit_cnt));
   NAND2_X1 U64 (.ZN(n130),
	.A2(P_to_plus1minus1[1]),
	.A1(P_to_plus1minus1[0]));
   AOI222_X1 U65 (.ZN(n150),
	.C2(n155),
	.C1(R_from_minus1[3]),
	.B2(n156),
	.B1(R_from_plus1[3]),
	.A2(n157),
	.A1(X[3]));
   INV_X1 U66 (.ZN(n90),
	.A(X[3]));
   AOI21_X1 U78 (.ZN(n127),
	.B2(bit_cnt),
	.B1(n122),
	.A(n121));
   AOI222_X1 U79 (.ZN(n161),
	.C2(n155),
	.C1(R_from_minus1[6]),
	.B2(n156),
	.B1(R_from_plus1[6]),
	.A2(n157),
	.A1(X[6]));
   AOI222_X1 U80 (.ZN(n154),
	.C2(n155),
	.C1(R_from_minus1[5]),
	.B2(n156),
	.B1(R_from_plus1[5]),
	.A2(n157),
	.A1(X[5]));
   AOI222_X1 U81 (.ZN(n152),
	.C2(n155),
	.C1(R_from_minus1[4]),
	.B2(n156),
	.B1(R_from_plus1[4]),
	.A2(n157),
	.A1(X[4]));
   AOI222_X1 U82 (.ZN(n148),
	.C2(n155),
	.C1(R_from_minus1[2]),
	.B2(n156),
	.B1(R_from_plus1[2]),
	.A2(n157),
	.A1(X[2]));
   AOI222_X1 U83 (.ZN(n146),
	.C2(n155),
	.C1(R_from_minus1[1]),
	.B2(n156),
	.B1(R_from_plus1[1]),
	.A2(n157),
	.A1(X[1]));
   AOI222_X1 U84 (.ZN(n144),
	.C2(n155),
	.C1(R_from_minus1[0]),
	.B2(n156),
	.B1(R_from_plus1[0]),
	.A2(n157),
	.A1(X[0]));
   AOI222_X1 U85 (.ZN(n142),
	.C2(n155),
	.C1(R_from_minus1[7]),
	.B2(n156),
	.B1(R_from_plus1[7]),
	.A2(n157),
	.A1(X[7]));
   AOI22_X1 U86 (.ZN(n125),
	.B2(n155),
	.B1(P_from_minus1[2]),
	.A2(n156),
	.A1(P_from_plus1[2]));
   AOI22_X1 U87 (.ZN(n120),
	.B2(n155),
	.B1(P_from_minus1[1]),
	.A2(n156),
	.A1(P_from_plus1[1]));
   INV_X1 U88 (.ZN(n102),
	.A(n129));
   OAI221_X1 U89 (.ZN(N51),
	.C2(n134),
	.C1(n135),
	.B2(n104),
	.B1(n102),
	.A(n133));
   OAI221_X1 U90 (.ZN(N50),
	.C2(n127),
	.C1(n103),
	.B2(n134),
	.B1(n124),
	.A(n123));
   INV_X1 U91 (.ZN(n101),
	.A(n121));
   OAI21_X1 U92 (.ZN(n129),
	.B2(n128),
	.B1(n131),
	.A(n127));
   NOR2_X1 U93 (.ZN(n157),
	.A2(n136),
	.A1(n4));
   NAND2_X1 U94 (.ZN(n74),
	.A2(n93),
	.A1(R_to_plus1minus1[7]));
   OAI21_X1 U95 (.ZN(n73),
	.B2(n98),
	.B1(X[6]),
	.A(n74));
   NAND3_X1 U96 (.ZN(n75),
	.A3(X[6]),
	.A2(n98),
	.A1(n74));
   OAI21_X1 U97 (.ZN(n78),
	.B2(n93),
	.B1(R_to_plus1minus1[7]),
	.A(n75));
   AND2_X1 U98 (.ZN(n83),
	.A2(n92),
	.A1(R_to_plus1minus1[5]));
   OR3_X1 U99 (.ZN(n76),
	.A3(n91),
	.A2(R_to_plus1minus1[4]),
	.A1(n83));
   OAI21_X1 U100 (.ZN(n77),
	.B2(n92),
	.B1(R_to_plus1minus1[5]),
	.A(n76));
   NAND2_X1 U102 (.ZN(n80),
	.A2(n90),
	.A1(R_to_plus1minus1[3]));
   OAI21_X1 U103 (.ZN(n79),
	.B2(X[2]),
	.B1(n95),
	.A(n80));
   NAND3_X1 U104 (.ZN(n81),
	.A3(X[2]),
	.A2(n95),
	.A1(n80));
   OAI21_X1 U105 (.ZN(n86),
	.B2(n90),
	.B1(R_to_plus1minus1[3]),
	.A(n81));
   AOI21_X1 U106 (.ZN(n82),
	.B2(n89),
	.B1(R_to_plus1minus1[1]),
	.A(R_to_plus1minus1[0]));
   AOI22_X1 U107 (.ZN(n84),
	.B2(X[0]),
	.B1(n82),
	.A2(n94),
	.A1(X[1]));
   AOI221_X1 U108 (.ZN(n85),
	.C2(n91),
	.C1(R_to_plus1minus1[4]),
	.B2(n97),
	.B1(n84),
	.A(n83));
   NAND2_X1 U7 (.ZN(n140),
	.A2(n136),
	.A1(n7));
   AND2_X1 U10 (.ZN(n155),
	.A2(n136),
	.A1(n137));
   AOI21_X1 U6 (.ZN(n117),
	.B2(n156),
	.B1(P_from_plus1[0]),
	.A(n165));
   AND3_X1 U9 (.ZN(n165),
	.A3(P_from_minus1[0]),
	.A2(n137),
	.A1(n136));
   NAND2_X1 U11 (.ZN(n137),
	.A2(T_from_minus1),
	.A1(n138));
   NOR2_X1 U12 (.ZN(n138),
	.A2(Z_from_minus1),
	.A1(n116));
   NAND2_X1 U14 (.ZN(T),
	.A2(n166),
	.A1(n167));
   AOI21_X1 U16 (.ZN(n166),
	.B2(n77),
	.B1(n99),
	.A(n78));
   OAI211_X1 U62 (.ZN(n167),
	.C2(n86),
	.C1(n96),
	.B(n99),
	.A(n85));
endmodule

module median_filter (
	srst, 
	clk, 
	X, 
	Y);
   input srst;
   input clk;
   input [7:0] X;
   output [7:0] Y;

   // Internal wires
   wire clk__L2_N7;
   wire clk__L2_N6;
   wire clk__L2_N5;
   wire clk__L2_N4;
   wire clk__L2_N3;
   wire clk__L2_N2;
   wire clk__L2_N1;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire FE_DBTN1_T_out_4_;
   wire FE_DBTN0_incre_en_3_;
   wire R_out_5__7_;
   wire R_out_5__6_;
   wire R_out_5__5_;
   wire R_out_5__4_;
   wire R_out_5__3_;
   wire R_out_5__2_;
   wire R_out_5__1_;
   wire R_out_5__0_;
   wire R_out_4__7_;
   wire R_out_4__6_;
   wire R_out_4__5_;
   wire R_out_4__4_;
   wire R_out_4__3_;
   wire R_out_4__2_;
   wire R_out_4__1_;
   wire R_out_4__0_;
   wire R_out_2__7_;
   wire R_out_2__6_;
   wire R_out_2__5_;
   wire R_out_2__4_;
   wire R_out_2__3_;
   wire R_out_2__2_;
   wire R_out_2__1_;
   wire R_out_2__0_;
   wire R_out_1__7_;
   wire R_out_1__6_;
   wire R_out_1__5_;
   wire R_out_1__4_;
   wire R_out_1__3_;
   wire R_out_1__2_;
   wire R_out_1__1_;
   wire R_out_1__0_;
   wire P_out_5__2_;
   wire P_out_5__1_;
   wire P_out_5__0_;
   wire P_out_4__2_;
   wire P_out_4__1_;
   wire P_out_4__0_;
   wire P_out_3__2_;
   wire P_out_3__1_;
   wire P_out_3__0_;
   wire P_out_2__2_;
   wire P_out_2__1_;
   wire P_out_2__0_;
   wire P_out_1__2_;
   wire P_out_1__1_;
   wire P_out_1__0_;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n49;
   wire n50;
   wire n52;
   wire [4:1] Z_out;
   wire [4:1] T_out;
   wire [3:0] cnt;
   wire [4:0] incre_en;

   CLKBUF_X3 clk__L2_I7 (.Z(clk__L2_N7),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I6 (.Z(clk__L2_N6),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I5 (.Z(clk__L2_N5),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I4 (.Z(clk__L2_N4),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I3 (.Z(clk__L2_N3),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I2 (.Z(clk__L2_N2),
	.A(clk__L1_N0));
   CLKBUF_X2 clk__L2_I1 (.Z(clk__L2_N1),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I0 (.Z(clk__L2_N0),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L1_I0 (.Z(clk__L1_N0),
	.A(clk));
   INV_X1 FE_DBTC1_T_out_4_ (.ZN(FE_DBTN1_T_out_4_),
	.A(T_out[4]));
   INV_X1 FE_DBTC0_incre_en_3_ (.ZN(FE_DBTN0_incre_en_3_),
	.A(incre_en[3]));
   DFF_X1 cnt_reg_0_ (.QN(n31),
	.Q(cnt[0]),
	.D(n47),
	.CK(clk__L2_N7));
   DFF_X1 cnt_reg_1_ (.QN(n30),
	.Q(cnt[1]),
	.D(n46),
	.CK(clk__L2_N7));
   DFF_X1 cnt_reg_2_ (.QN(n29),
	.Q(cnt[2]),
	.D(n45),
	.CK(clk__L2_N7));
   NAND3_X1 U25 (.ZN(n34),
	.A3(n36),
	.A2(n29),
	.A1(n35));
   NAND3_X1 U26 (.ZN(n38),
	.A3(n36),
	.A2(n30),
	.A1(cnt[0]));
   unit_cell_R_WIDTH8_N5_P_WIDTH3_0 unit_cell_gen_1__unit_cell (.srst(srst),
	.clk(clk__L2_N3),
	.incre_en(incre_en[0]),
	.X(X),
	.R_from_plus1({ R_out_2__7_,
		R_out_2__6_,
		R_out_2__5_,
		R_out_2__4_,
		R_out_2__3_,
		R_out_2__2_,
		R_out_2__1_,
		R_out_2__0_ }),
	.R_from_minus1({ R_out_1__7_,
		R_out_1__6_,
		R_out_1__5_,
		R_out_1__4_,
		R_out_1__3_,
		R_out_1__2_,
		R_out_1__1_,
		R_out_1__0_ }),
	.P_from_plus1({ P_out_2__2_,
		P_out_2__1_,
		P_out_2__0_ }),
	.P_from_minus1({ P_out_1__2_,
		P_out_1__1_,
		P_out_1__0_ }),
	.Z_from_minus1(1'b0),
	.T_from_minus1(1'b0),
	.R_to_plus1minus1({ R_out_1__7_,
		R_out_1__6_,
		R_out_1__5_,
		R_out_1__4_,
		R_out_1__3_,
		R_out_1__2_,
		R_out_1__1_,
		R_out_1__0_ }),
	.P_to_plus1minus1({ P_out_1__2_,
		P_out_1__1_,
		P_out_1__0_ }),
	.Z_to_plus1(Z_out[1]),
	.T_to_plus1(T_out[1]),
	.clk__L2_N2(clk__L2_N2),
	.clk__L2_N6(clk__L2_N6),
	.clk__L2_N7(clk__L2_N7));
   unit_cell_R_WIDTH8_N5_P_WIDTH3_4 unit_cell_gen_2__unit_cell (.srst(srst),
	.clk(clk__L2_N3),
	.incre_en(incre_en[1]),
	.X(X),
	.R_from_plus1(Y),
	.R_from_minus1({ R_out_1__7_,
		R_out_1__6_,
		R_out_1__5_,
		R_out_1__4_,
		R_out_1__3_,
		R_out_1__2_,
		R_out_1__1_,
		R_out_1__0_ }),
	.P_from_plus1({ P_out_3__2_,
		P_out_3__1_,
		P_out_3__0_ }),
	.P_from_minus1({ P_out_1__2_,
		P_out_1__1_,
		P_out_1__0_ }),
	.Z_from_minus1(Z_out[1]),
	.T_from_minus1(T_out[1]),
	.R_to_plus1minus1({ R_out_2__7_,
		R_out_2__6_,
		R_out_2__5_,
		R_out_2__4_,
		R_out_2__3_,
		R_out_2__2_,
		R_out_2__1_,
		R_out_2__0_ }),
	.P_to_plus1minus1({ P_out_2__2_,
		P_out_2__1_,
		P_out_2__0_ }),
	.Z_to_plus1(Z_out[2]),
	.T_to_plus1(T_out[2]),
	.clk__L2_N2(clk__L2_N2),
	.clk__L2_N6(clk__L2_N6),
	.clk__L2_N7(clk__L2_N7));
   unit_cell_R_WIDTH8_N5_P_WIDTH3_3 unit_cell_gen_3__unit_cell (.srst(srst),
	.clk(clk__L2_N4),
	.incre_en(incre_en[2]),
	.X(X),
	.R_from_plus1({ R_out_4__7_,
		R_out_4__6_,
		R_out_4__5_,
		R_out_4__4_,
		R_out_4__3_,
		R_out_4__2_,
		R_out_4__1_,
		R_out_4__0_ }),
	.R_from_minus1({ R_out_2__7_,
		R_out_2__6_,
		R_out_2__5_,
		R_out_2__4_,
		R_out_2__3_,
		R_out_2__2_,
		R_out_2__1_,
		R_out_2__0_ }),
	.P_from_plus1({ P_out_4__2_,
		P_out_4__1_,
		P_out_4__0_ }),
	.P_from_minus1({ P_out_2__2_,
		P_out_2__1_,
		P_out_2__0_ }),
	.Z_from_minus1(Z_out[2]),
	.T_from_minus1(T_out[2]),
	.R_to_plus1minus1(Y),
	.P_to_plus1minus1({ P_out_3__2_,
		P_out_3__1_,
		P_out_3__0_ }),
	.Z_to_plus1(Z_out[3]),
	.T_to_plus1(T_out[3]),
	.clk__L2_N3(clk__L2_N3),
	.clk__L2_N2(clk__L2_N2),
	.clk__L2_N1(clk__L2_N1),
	.clk__L2_N5(clk__L2_N5),
	.clk__L2_N6(clk__L2_N6),
	.clk__L2_N7(clk__L2_N7));
   unit_cell_R_WIDTH8_N5_P_WIDTH3_2 unit_cell_gen_4__unit_cell (.srst(srst),
	.clk(clk__L2_N4),
	.incre_en(incre_en[3]),
	.X(X),
	.R_from_plus1({ R_out_5__7_,
		R_out_5__6_,
		R_out_5__5_,
		R_out_5__4_,
		R_out_5__3_,
		R_out_5__2_,
		R_out_5__1_,
		R_out_5__0_ }),
	.R_from_minus1(Y),
	.P_from_plus1({ P_out_5__2_,
		P_out_5__1_,
		P_out_5__0_ }),
	.P_from_minus1({ P_out_3__2_,
		P_out_3__1_,
		P_out_3__0_ }),
	.Z_from_minus1(Z_out[3]),
	.T_from_minus1(T_out[3]),
	.R_to_plus1minus1({ R_out_4__7_,
		R_out_4__6_,
		R_out_4__5_,
		R_out_4__4_,
		R_out_4__3_,
		R_out_4__2_,
		R_out_4__1_,
		R_out_4__0_ }),
	.P_to_plus1minus1({ P_out_4__2_,
		P_out_4__1_,
		P_out_4__0_ }),
	.Z_to_plus1(Z_out[4]),
	.T_to_plus1(T_out[4]),
	.p(FE_DBTN0_incre_en_3_),
	.clk__L2_N0(clk__L2_N0),
	.clk__L2_N1(clk__L2_N1),
	.clk__L2_N5(clk__L2_N5));
   unit_cell_R_WIDTH8_N5_P_WIDTH3_1 unit_cell_gen_5__unit_cell (.srst(srst),
	.clk(clk__L2_N0),
	.incre_en(incre_en[4]),
	.X(X),
	.R_from_plus1({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0 }),
	.R_from_minus1({ R_out_4__7_,
		R_out_4__6_,
		R_out_4__5_,
		R_out_4__4_,
		R_out_4__3_,
		R_out_4__2_,
		R_out_4__1_,
		R_out_4__0_ }),
	.P_from_plus1({ 1'b0,
		1'b0,
		1'b0 }),
	.P_from_minus1({ P_out_4__2_,
		P_out_4__1_,
		P_out_4__0_ }),
	.Z_from_minus1(Z_out[4]),
	.T_from_minus1(FE_DBTN1_T_out_4_),
	.R_to_plus1minus1({ R_out_5__7_,
		R_out_5__6_,
		R_out_5__5_,
		R_out_5__4_,
		R_out_5__3_,
		R_out_5__2_,
		R_out_5__1_,
		R_out_5__0_ }),
	.P_to_plus1minus1({ P_out_5__2_,
		P_out_5__1_,
		P_out_5__0_ }),
	.clk__L2_N1(clk__L2_N1),
	.clk__L2_N5(clk__L2_N5));
   DFF_X1 cnt_reg_3_ (.QN(n28),
	.Q(cnt[3]),
	.D(n49),
	.CK(clk__L2_N5));
   NOR2_X1 U27 (.ZN(n49),
	.A2(FE_DBTN0_incre_en_3_),
	.A1(srst));
   INV_X1 U29 (.ZN(n52),
	.A(n36));
   AND2_X1 U30 (.ZN(n40),
	.A2(n42),
	.A1(n41));
   AOI21_X1 U31 (.ZN(n36),
	.B2(cnt[3]),
	.B1(cnt[2]),
	.A(srst));
   OAI21_X1 U32 (.ZN(n37),
	.B2(n52),
	.B1(cnt[0]),
	.A(n39));
   OAI22_X1 U33 (.ZN(n47),
	.B2(n52),
	.B1(cnt[0]),
	.A2(n39),
	.A1(n31));
   OAI21_X1 U34 (.ZN(n46),
	.B2(n30),
	.B1(n50),
	.A(n38));
   INV_X1 U35 (.ZN(n50),
	.A(n37));
   OAI21_X1 U36 (.ZN(n45),
	.B2(n29),
	.B1(n33),
	.A(n34));
   AOI21_X1 U37 (.ZN(n33),
	.B2(n30),
	.B1(n36),
	.A(n37));
   XNOR2_X1 U40 (.ZN(n44),
	.B(n30),
	.A(cnt[0]));
   NOR2_X1 U41 (.ZN(n35),
	.A2(n30),
	.A1(n31));
   OAI21_X1 U42 (.ZN(incre_en[3]),
	.B2(n42),
	.B1(n41),
	.A(n28));
   AOI21_X1 U43 (.ZN(n41),
	.B2(cnt[2]),
	.B1(n44),
	.A(n35));
   XNOR2_X1 U44 (.ZN(n42),
	.B(n44),
	.A(cnt[2]));
   OAI21_X1 U45 (.ZN(incre_en[2]),
	.B2(n29),
	.B1(n43),
	.A(n28));
   NOR2_X1 U46 (.ZN(n43),
	.A2(cnt[1]),
	.A1(cnt[0]));
   NOR2_X1 U47 (.ZN(incre_en[4]),
	.A2(n28),
	.A1(n40));
   OR3_X1 U48 (.ZN(incre_en[1]),
	.A3(n35),
	.A2(cnt[3]),
	.A1(cnt[2]));
   NAND2_X1 U49 (.ZN(incre_en[0]),
	.A2(n28),
	.A1(n40));
   OR2_X1 U38 (.ZN(n39),
	.A2(n36),
	.A1(srst));
endmodule

